import Head from 'next/head'
import Header from '../components/Header'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Hulu 2.0 (Miauri)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />
      <h1 className='red w-10 h-8 underline'>HOLA MUNDO</h1>
      {/* Nav */}

      {/* Results */}
    </div>
  )
}
